server:
  port: 9959
spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
mybatis-plus:
  mapper-locations: classpath*:com/gaofeicm/qqbot/dao/*Mapper.xml
jasypt:
  encryptor:
    password:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
serviceAddress:
maiarkAddress:
admin:
  qq:
task:
  cron:
    ck:
      checkLogin: 0 0 0/2 * * ?