server:
  port: 9000
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
mybatis-plus:
  mapper-locations: classpath*:com/gaofeicm/qqbot/dao/*Mapper.xml
jasypt:
  encryptor:
    password:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
jpk:
  appId:
  appKey:
  unionId:
serviceAddress:
jpkServiceAddress:
jpkServiceEnable:
maiarkAddress:
admin:
  qq:
task:
  cron:
    ck:
      checkLogin: 0 0 0/2 * * ?
      checkLogout: 0 0 12 ? * SUN
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId:  # 第一个公众号的appid
        secret:  # 公众号的appsecret
        token:  # 接口配置里的Token值
        aesKey:  # 接口配置里的EncodingAESKey值